{"uid":"d1bb0fb9f8e15312","name":"[COLUMN] As a user, I should check the validation of DATETIME column definition","fullName":"JIT-Database-008-COLUMN-type-DATE-TIME.[COLUMN] As a user, I should check the validation of DATETIME column definition","historyId":"8da63a174879582a7f78bb5d0c35ac57","time":{"start":1658398240400,"stop":1658398318526,"duration":78126},"description":"","descriptionHtml":"","status":"broken","statusMessage":"Error: [JITERA] - Could not create project with nameJITDatabase0081010578084965e2e. Error: Error: Request failed with status code 504","statusTrace":"Error: [JITERA] - Could not create project with nameJITDatabase0081010578084965e2e. Error: Error: Request failed with status code 504\n                    at APIProject.<anonymous> (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:70:13)\n                    at step (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:48:23)\n                    at Object.throw (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:29:53)\n                    at rejected (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:21:65)\n                    at processTicksAndRejections (node:internal/process/task_queues:96:5)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"Error: [JITERA] - Could not create project with nameJITDatabase0081010578084965e2e. Error: Error: Request failed with status code 504","statusTrace":"Error: [JITERA] - Could not create project with nameJITDatabase0081010578084965e2e. Error: Error: Request failed with status code 504\n                    at APIProject.<anonymous> (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:70:13)\n                    at step (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:48:23)\n                    at Object.throw (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:29:53)\n                    at rejected (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:21:65)\n                    at processTicksAndRejections (node:internal/process/task_queues:96:5)","steps":[{"name":"Given I am login on staging env by created timestamp project","time":{"start":1658398240405,"stop":1658398318526,"duration":78121},"status":"broken","statusMessage":"Error: [JITERA] - Could not create project with nameJITDatabase0081010578084965e2e. Error: Error: Request failed with status code 504\n                    at APIProject.<anonymous> (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:70:13)\n                    at step (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:48:23)\n                    at Object.throw (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:29:53)\n                    at rejected (/home/runner/work/test-github-action/test-github-action/features/apis/apis-function/api-project/api.project.ts:21:65)\n                    at processTicksAndRejections (node:internal/process/task_queues:96:5)","steps":[{"name":"Debug step: ","time":{"start":1658398257805,"stop":1658398257808,"duration":3},"status":"passed","steps":[],"attachments":[{"uid":"5763847e09fa1f63","name":"Project was cleaned","source":"5763847e09fa1f63.txt","type":"text/plain","size":15}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"6b279bd19505fdf1","name":"Screenshot","source":"6b279bd19505fdf1.png","type":"image/png","size":33692}],"parameters":[],"stepsCount":1,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":2,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"framework","value":"wdio"},{"name":"language","value":"javascript"},{"name":"thread","value":"0-57"},{"name":"suite","value":"JIT-Database-008-COLUMN-type-DATE-TIME"},{"name":"testClass","value":"JIT-Database-008-COLUMN-type-DATE-TIME"},{"name":"testMethod","value":"[COLUMN] As a user, I should check the validation of DATETIME column definition"},{"name":"package","value":"JIT-Database-008-COLUMN-type-DATE-TIME"},{"name":"resultFormat","value":"allure1"}],"parameters":[{"name":"browser","value":"chrome-103.0.5060.114"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e675080c83274b1b","status":"broken","statusDetails":"Error: element (\".ant-btn-loading-icon\") still displayed after 45000ms","time":{"start":1658391585407,"stop":1658391708471,"duration":123064}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d1bb0fb9f8e15312.json","parameterValues":["chrome-103.0.5060.114"]}